import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import Loader from '../components/Loader';
import toast from 'react-hot-toast';

export default function Home() {
	return (
		<div>
			<Head>
				<title>NextFire</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<button onClick={() => toast.success('Hello')}>Toast</button>
		</div>
	);
}
