import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
	return (
		<div>
			<Head>
				<title>NextFire</title>

				<meta name="description" content="Generated by create next app" />
			</Head>

			<Link
				prefetch={false}
				href={{
					pathname: '/[username]',
					query: { username: 'Chris A' },
				}}
			>
				<a>Chris's Profile</a>
			</Link>
		</div>
	);
}
